[package]
name = "leetcode"
version = "0.1.0"
authors = ["lonelyhentai <master@evernightfireworks.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
simple-error = "0.2.3"
lazy_static = "1.4.0"
regex = "1.4.3"
